// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'code': string;
  'dark': string;
  'light': string;
  'root': string;
  'themeToggle': string;
}
export const cssExports: CssExports;
export default cssExports;
